### ISSUE TITLE
Wrong volume with AlignedTime rule aggregation

### ISSUE THREAD

**Issue by ivaaaan** [MathisWellmann/trade_aggregation-rs#12]
Hey. I have noticed that after using `AlignedTime` aggregation rule volume and amount of trades look wrong. Here is a simple test case:

https://github.com/ivaaaan/trade_aggregation-rs/blob/wrong-volume/src/aggregation_rules/aligned_time_rule.rs#L112

And test data file:
https://github.com/ivaaaan/trade_aggregation-rs/blob/wrong-volume/data/Bitstamp_BTCEUR_1M.csv

There are 10 trades between `00:00:00` and `00:00:01`, however, aggregation rule includes 11th trade from the next minute as well.

**Comment by ivaaaan** [comment]
I assume this should fix the problem: https://github.com/MathisWellmann/trade_aggregation-rs/pull/13

Candle shouldn't be updated before the trigger

**Comment by ivaaaan** [comment]
Related commit: e7e2424ab7d1814f70cc40ef863243c2d5e4e840
It used to be like this but changed ff766c09970fce40f34527a628d9549b3e9f428f

**Comment by MathisWellmann** [comment]
Thanks for raising this. I'll look into your PRs during this week. Setting up CI on my end to make the process better.

**Comment by ivaaaan** [comment]
Fixed in #13
