### ISSUE TITLE
Thoughts on making Trade Generic or Adding a BidAskTrade?

### ISSUE THREAD

**Issue by dam5h** [MathisWellmann/trade_aggregation-rs#2]
Just came across this library, looks great, thank you!

I store tick data that has the bid / ask aggressor flag in it for order flow analysis.  What are your thoughts on making the input `Trade` struct be be generic or just adding a variant that has additional information about whether or not it was a bid or ask trade?

As far as making `Trade` generic, I suppose a trait with getters for the required fields could work, then folks that have there own structures being read in wouldn't have to transform into `Trade` on every `update` call if they implement the trait.

Let me know what you think when you get a chance.  Thanks again for this library.  Have a nice day.

**Comment by MathisWellmann** [comment]
Hi Dave, 
I appreciate the input.
So in your case I would recommend you directly encode your bid / ask aggressor flag into the size field of the Trade, where a market sell order (which is taking the bid) is a negative number. This has been the core idea idea in my design. 
However, there could be a trait of the form:
```rust
pub trait Trade {
  fn timestamp(&self) -> i64;
  fn price(&self) -> f64;
  fn size(&self) -> f64;
}
```
For some CandleComponents It would still be required for the size to be negative for market sell trades such as the DirectionalVolumeRatio as it's designed with this in mind.

But I suppose it doesn't matter as you can pick which CandleComponents you want so most of them don't actually care about the size of a trade at all.

So I'm open to seeing a pull request from you If you'd like to implement this idea.

Have a nice weekend!

**Comment by MathisWellmann** [comment]
I'd like to keep the Trade struct however as my entire trading pipeline depends on it. So I recommend to name the trait TakerTrade maybe as it clarifies the nature of the trade as well.

**Comment by dam5h** [comment]
Ah, that is a good idea re: having the quantity signed and would actually save me a byte on my record size as well.  The trait would probably still be useful to avoid those transformations and I assume it doesn't add any overhead (especially compared to any transformation) as a getter in release mode, do you have any insight on that part?  Happy to put together a PR for the trait, thanks for offering that up.

Cheers!

**Comment by dam5h** [comment]
@MathisWellmann , So I did add the generic to the `ModularCandle` trait, but now I am running into issues on the `derive` macro side of things.  I am fairly new to rust and haven't written any macros myself.  It looks like `derive` macros can't take arguments (such as the user type which `ModularCandle` is to be generic over.  However there are some work arounds for this from what I can tell, such as using attributes on the custom derive macro.  

I wanted to play around with this idea a bit, but I am having a heck of a time just getting `cargo expand` to play nicely so I can test my edits to the derive macro implementation.  It seems that even after `cargo clean` and `cargo clean -p trade_aggregation_derive` I am not seeing my edits to the `trade_aggregation_derive` package.  I added a `main.rs` file just so I could play with `cargo expand --bin trade-aggregation`.  But I keep getting old expanded output even after making edits, so I am a little confused.

Do you have any insights on the best way to add the type input into the `ModularCandle<T>` impl that would be getting autogenerated?

The branch I am exploring this idea on is `generic-not-AT` over on my [fork](https://github.com/dam5h/trade_aggregation-rs/tree/generic-not-AT).  

Separately I do think that having a generic input to the aggregators and candles is useful, I realized that you could use this for resampling existing candles to higher timeframes as well, for users that may not have tick data available, such as 1sec candles or something like that.  

Cheers!

 EDIT: I did resolve the issue with it not loading/updating when changes made to the nested derive crate, I (of course) needed to use the path declaration to point to the local `trade_aggregation_derive`
 
 ```
 trade_aggregation_derive = {path="trade_aggregation_derive"}
```

**Comment by MathisWellmann** [comment]
Really great job on this! 
I've checked out your "generic-not-AT" branch and it is essentially what I would have done with this as well. 
I'll merge the changes, clean up some minor details (like annotating with #[inline(always)] which helps performance noticably) and publish this as version 5.0.0 to crates.io when ready, so you can rely on it for your project as well.

Thanks for this great contribution and happy trading Dave!

**Comment by dam5h** [comment]
Thanks Mathis!  Sounds good on the merge.  Just so you know I was actually planning on cleaning this up a bit more and also trying to get the derive macro to work for downstream types (as now we are hardcoding `Trade` into `ModularCandle`.  I can play with this and submit a second PR if that sounds reasonable.  Probably won't be until next week though as I am headed out of town in the morning.

Cheers and happy trading to you as well!

**Comment by MathisWellmann** [comment]
Sure thing. Feel free to tinker with it some more. Make sure you pull from my master again when building more changes on top, so your branch is all up to date with the newest v5 release
